language: go
go:
 - 1.3.3
 - 1.4.2
 - 1.5.1
 - tip

script:
 - go test -v ./...
 - go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -i sh -c {}
 - gover . coverprofile.txt
